#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# so all binaries are visible in dmenu_run
export PATH="$PATH:$HOME/.yadr/i3/bin:$HOME/.bin:$HOME/bin"

# Load Xresources
# xrdb -merge ~/.yadr/i3/Xresources
xrdb I$HOME ~/.yadr/i3/Xresources

# multiple screen setup
[ -e ~/.screen_setup ] && source ~/.screen_setup

# background
[ -e ~/.fehbg ] && source ~/.fehbg

# hide mouse coursor when it isn't used
unclutter -root -visible &

# pulse audio session
start-pulseaudio-x11

# keyboard layout
# xmodmap ~/.yadr/i3/xmodmap
# [ -e ~/.xmodmap_local ] && xmodmap ~/.xmodmap_local

setxkbmap us
setxkbmap -option caps:escape &

# color temperature adjustment, set for Gdańsk
redshift -l 41.38:2.18 -m randr -t 5500:3500 -g 0.75:0.75:0.75 &

# notification
dunst -config ~/.yadr/i3/dunstrc &

# disks automounting
udiskie &

# terminal server
urxvtd &

# dropbox
[ -e /usr/bin/dropboxd ] && /usr/bin/dropboxd &

# gpg agent
export SSH_AUTH_SOCK="${HOME}/.gnupg/S.gpg-agent.ssh"
gpg-connect-agent updatestartuptty /bye

# composition manager
compton --config ~/.yadr/i3/compton.conf &

# Network Manager applet
>> /dev/null which nm-applet && nm-applet &
>> /dev/null which blueman--applet && blueman-applet &

# Clipboard
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# Enable numlock
numlockx

xcape

i3

true
